Push-to-talk V3
inworld-ai/inworld-unity-sdk pull request #118
Opened 2023-09-18 16:57 UTC by mattkwilson

- Updated AudioCapture system
- Modified PlayerController and inherited scripts with push-to-talk options

2023-09-19 23:13 UTC, Juniverse approved these changes

2023-09-27 17:53 UTC, mattkwilson commented
Lots of changes in this pull request:

- Updated AudioCapture script and audio capture handling
- Moved character handling from InworldController into new CharacterHandler script
- Moved AudioCapture handling from InworldClient to InworldController
- Refactored PlayerController scripts into PlayerController, PlayerController2D, PlayerController3D, PlayerControllerInnequin and PlayerControllerRPM
- Updated all related scenes and prefabs with these changes
- Fixed bugs and UI issues related to: https://inworldai.atlassian.net/browse/CORE-3891

2023-09-27 19:58 UTC, Juniverse requested changes
Overall looks good. Please reduce static classes, like `AudioCapture` and `CharacterSeleter` put them as reference of `InworldController`

2023-09-27 19:58 UTC, Juniverse commented on Assets/Inworld/Inworld.AI/Scripts/InworldController.cs
> +    [RequireComponent(typeof(AudioCapture))]
No need to add this, InworldClient has require component for audio capture.

2023-09-27 19:58 UTC, Juniverse commented on Assets/Inworld/Inworld.AI/Scripts/CharacterHandler.cs
> +    public class CharacterHandler : SingletonBehavior<CharacterHandler>
Same as AudioCapture, as long as it's in the same `InworldController.prefab`, no need to set as singleton because `InworldController` is already a singleton.

2023-09-27 19:58 UTC, Juniverse commented on Assets/Inworld/Inworld.AI/Scripts/InworldController.cs
> +        public bool IsPlayerSpeaking => m_AudioCapture.PlayerIsSpeaking;
You can get rid of these two as long as `InworldController` has AudioCapture reference.

2023-09-27 19:58 UTC, Juniverse commented on Assets/Inworld/Inworld.AI/Scripts/Interaction/InworldAudioInteraction.cs
> +            float targetVolume = InworldController.Instance.IsPlayerSpeaking ? m_VolumeOnPlayerSpeaking : 1f;
Should be InworldController.Audio.IsPlayerSpeaking

2023-09-27 19:58 UTC, Juniverse commented on Assets/Inworld/Inworld.AI/Scripts/CharacterHandler.cs
> +
Need to have basic handling. Otherwise Unity asset store will not approve because of warning "e" is not used.

2023-09-27 19:58 UTC, Juniverse commented on Assets/Inworld/Inworld.Samples.RPM/Scripts/UI/SessionCanvas.cs
> +using UnityEngine.Serialization;
Remove redundent namespace

2023-09-27 23:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/inworld-ai/inworld-unity-sdk?pullRequest=118) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/inworld-ai/inworld-unity-sdk?pullRequest=118) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inworld-ai/inworld-unity-sdk?pullRequest=118) it.</sub>

2023-09-28 00:13 UTC, mattkwilson commented on Assets/Inworld/Inworld.AI/Scripts/InworldController.cs
> +    [RequireComponent(typeof(AudioCapture))]
I removed this line from InworldClient

2023-09-28 15:58 UTC, merged