Scene selection optional
inworld-ai/inworld-unity-sdk pull request #58
Opened 2023-04-11 03:19 UTC by Div-Inworld

2023-04-11 04:59 UTC, Juniverse commented
1. The button looks too hacky, please add `all characters` into the scene selection, instead of the gui button.
2. After selecting a regular scene, then click `Download all characters`, there is a UI error. The sceneName is replaced with key name.
![image](https://user-images.githubusercontent.com/68676221/231060095-87b4de8c-6558-446d-9b02-cd304da9e328.png)
3. After played with 2 characters in the Unity scene, and then click open studio panel, it showcases data is missing and the characters aren't able to be loaded.
![image](https://user-images.githubusercontent.com/68676221/231060445-b472dd95-77c0-4a5c-9362-4c2a704228a1.png)

2023-04-11 05:02 UTC, Juniverse requested changes
1. Please update UI, put `all characters` into scene selection list.
2. Please fix those UI bugs.

2023-05-18 22:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/inworld-ai/inworld-unity-sdk?pullRequest=58) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/inworld-ai/inworld-unity-sdk?pullRequest=58) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inworld-ai/inworld-unity-sdk?pullRequest=58) it.</sub>

2023-08-03 15:00 UTC, Div-Inworld commented
obsolete implementation causing conflicts/bugs

2023-08-03 15:00 UTC, closed without merging